### ISSUE TITLE
GraphWorker: The graph example is not rendering properly.

### ISSUE THREAD

**Issue by frankwan41** [MotivationalModelling/mm-local-editor#7]
The example graph fails to render when the application starts. However, after refreshing the code, the graph appears, but the vertices do not function correctly—such as updating colors, modifying label text, etc.

The code associate is [Here](https://github.com/MotivationalModelling/mm-local-editor/blob/29825dc5f015f81c7d2c55dbd84184ec8d590f4a/src/components/Graphs/GraphWorker.tsx#L997C1-L1069C8)

**Comment by thomasjtHe** [comment]
Graph Example Render issue fixed, but it seems that the editor can't operate properly with the graph example. Namely, the editor won't display the graph you create when the example graph is at present. I think we better prioritize this before moving on to implementing the rendering function, otherwise the rendering would be hard to test.
